[other]
	# Download packages
      DownloadPackage = false # <true> For first time user download packages required to run program; <false>*

	# Plotting
      Ploting    = true # <true>* plot; <false> no plotting
      PlotVscode = true # <true>* plot shown in VScode; <false>

[data]
   HydroParam            = false # <true> ; <false>
   Infilt                = true # <true> ; <false>
   Jules                 = false # <true> or <false>
   "Kθ"                  = true # <true> ; <false>
   "Pedological⍰"        = ":Core" # <:Core>; from traditional data set <:Smap> from Smap; <No> no data available
   Psd                   = true # <true> ; <false>
   RockWetability        = true # <true> ; <false>
   "SimulationKosugiθΨK" = false # <true> or <false>
   "θΨ"                  = true # <true> ; <false>
   "Φ⍰"                  = ":ρᵦ" # <:ρᵦ> BulkDensity data; <:Φ> TotalPorosity; <:No> no data

[run]
	ChangeHydroModel       = false # TODO Not yet operational<true>; <false>
	"HydroLabθΨ⍰"            = ":No" # <:Opt>* Optimize hydraulic parameters from θ(Ψ); <:File> from save file; <:Run> just run <:No> not available
	Hypix                  = false # cannot run simultaneously with other modules <true>; <false>
	Infilt                 = false # <true>; <false>
	IntergranularMixingPsd = false # <true>; <false>
	Jules                  = false # <true>; <false>
	RockCorection          = false # <true> make correction for rock fragment; <false> no correction for rock fragment
	Smap                   = false  # <true>; <false>
	Smap2Hypix             = false
	Temporary              = true # <true>; <false>

[rockFragment]		
	CorectStoneRockWetability = false # <true> rocks are wettable; <false> rocks are mot wettable 
	"RockInjectedIncluded⍰" = ":InjectRock" # <:InjectRock> rocks fragments are injected/forced into the fine soils; <Included> rocks are included in the bulk BulkDensity

[smap]			
	Nothings = false  # <true> or <false>

[hydro]
	"HydroModel⍰"      = ":Kosugi" # <:Kosugi>*; <:Vangenuchten>; <:BrooksCorey>; <:ClappHornberger>; <:VangenuchtenJules>
	# HydroModel_List = [:Kosugi; :Vangenuchten; :BrooksCorey; :ClappHornberger; :VangenuchtenJules]
	HydroModel_List = "[:Kosugi]"
		"θsOpt⍰"           = ":Φ" #  <:Opt> Optimize θs; <:Φ> derived from total porosity which requires some correction from param.hydro.Coeff_Φ_2_θs; <:FromData> θs is optimised with the feasible range derived directly from θobs(Ψ), assuming that we have θ(Ψ=0))
		"θrOpt⍰"           = ":Opt" # <:Opt> optimises; <:ParamPsd> derive from PSD and uses α1 and α1 from parameters in Param.jl; <:σ_2_θr>	
		"σ_2_Ψm⍰"          = ":Constrained" # <:Constrained> Ψm physical feasible range is computed from σ <:UniqueRelationship> Ψm is computed from σ; <:No> optimisation of σ & Ψm with no constraints
	# PLOTTING
		"Plot_θΨ"   = true

[psd]		
	"Model⍰"      = ":IMP" # <:IMP>* Intergranular Mixing Model⍰; <:Chang2019Model>
	"OptimizePsd⍰" = ":OptAllSoil" # <:OptSingleSoil>; <:OptAllSoil>; or <:Run>
	"Psd_2_θr⍰"    = ":Opt" # <:Opt> optimises parameters α1 and α1; <:ParamPsd> uses α1 and α1 from parameters in Param.jl

	# For OptimizePsd⍰ = :single
	"∑Psd_2_ξ1" = true  # <true> optimize ξ1; <false>

	# FITTING THE PSD FUNCTION TO A HYDRAULIC MODEL			
	"HydroModel⍰" = ":Kosugi" # <:Kosugi>*; <:Vangenuchten>; <:BrooksCorey>; <:ClappHornberger>; <:VangenuchtenJules>

	"θsOpt⍰"      = ":Φ" #  <:Opt> Optimize θs; <:Φ> derived from total porosity which requires some correction from param.hydro.Coeff_Φ_2_θs; <:FromData> θs is optimised with the feasible range derived directly from θobs(Ψ), assuming that we have θ(Ψ=0))
	"θrOpt⍰"      = ":Opt" # <:Opt> optimises; <:ParamPsd> derive from PSD and uses α1 and α1 from parameters in Param.jl; <:σ_2_θr>
	"σ_2_Ψm⍰"     = ":Constrained" # <:Constrained> Ψm physical feasible range is computed from σ <:UniqueRelationship> Ψm is computed from σ; <:No> optimisation of σ & Ψm with no constraints

	# PLOTTING
	"Plot_Psd_θΨ"    = true # <true>  plot θΨ of PSD; <false>
	"Plot_θr"        = true #  <true>  plot θr data and model from Psd ; <false>	
	Plot_IMP_Model = true # <true> ; plot IMP model results for publication; <false>

	# TABLE
	"Table_Psd_θΨ_θ" = true # <true> derive θ values at prescribed Ψ

[infilt]	
	"DataSingleDoubleRing⍰" = ":Double"	# <:Double> infiltration measured by double ring infiltrometer; <:Single> infiltration measured by single ring infiltrometer
	"OptimizeRun⍰"          = ":Opt" # <:Opt>* Optimise hydraulic parameters from infiltration data; <:Run> run inftration curves from known hydraulic parameters; <:RunOptKs>  run inftration curves from known hydraulic parameters but optimize Ks only
	"Model⍰"                = ":QuasiExact" 	# <:QuasiExact> physical approach; <:Best_Univ> statistical improved approach
	BestUniv_Continous    = true # <true> if the function is continous as recommended; <false> traditional
	"SorptivitySplitModel⍰" = ":Split" # <:Split>; <:Split_η>
	"SorptivityModel⍰"      = ":Parlange" # <:Parlange> strong non-linear diffusivity;  <:Crank> constant diffusivity; <:Philip_Knight> dirac delta-function diffusivity; <:Brutsaert> moderate non-linear diffusivity,

	# Deriving hydraulic parameters from infiltration tests
	"HydroModel⍰"      = ":Kosugi" # <:Kosugi>*; <:Vangenuchten>; <:BrooksCorey>; <:ClappHornberger>; <:VangenuchtenJules>

	"θsOpt⍰"           = ":Φ" #  <:Opt> Optimize θs; <:Φ> derived from total porosity which requires some correction from param.hydro.Coeff_Φ_2_θs; <:FromData> θs is optimised with the feasible range derived directly from θobs(Ψ), assuming that we have θ(Ψ=0))
	"θrOpt⍰"           = ":Opt" # <:Opt> optimises; <:ParamPsd> derive from PSD and uses α1 and α1 from parameters in Param.jl; <:σ_2_θr>	
	"σ_2_Ψm⍰"          = ":Constrained" # <:Constrained> Ψm physical feasible range is computed from σ <:UniqueRelationship> Ψm is computed from σ; <:No> optimisation of σ & Ψm with no constraints

	# Plotting
	Plot_Sorptivity       = true # <true> or <false>	
	"Plot_∑Infilt"          = true # <true> plots cumulative infiltration curves for experimental and derived data <false> no plots
	"Plot_θΨ"               = true # <true>; <false>

[hyPix]
	# Time step
	"ClimateDataTimestep⍰" = ":Daily" # <:Hourly>; <:Daily>

	# Modules used
	RainfallInterception = true
	Evaporation          = true
	RootWaterUptake      = true
	RootWaterUptakeComp  = true

	#S sink term 
	LookupTable_Lai            = true # <false> Lai=constant; <true> Lai varies per month
	LookUpTable_CropCoeficient = true # <false> CropCoeficient=constant; <true> CropCoeficient varies per month

	# Hydraulic model 
	"HydroModel⍰" = ":Kosugi" # <:vanGenuchten>; <:Kosugi>

	# Richards equation
	"BottomBoundary⍰" = ":Free" # not working <:Free>; <:Pressure>
	"∂R∂Ψ_Numerical" = false # perform the derivatives numerically <true>; <false>

	# Adaptive time step
	"AdaptiveTimeStep⍰"   = ":ΔΨ" # <:ΔΨ>; <:Δθ>
	"NormMin⍰"            = ":Norm"		#<:Norm>; <:Min>
	Flag_ReRun         = true # <true>; <false> Rerun after updating the ΔT
	Qbottom_Correction = true # <true> correction for the mass balance of the last cell
	# const NoConverge_Ψbest   = false # not working <true>; <false>* compute Q(Ψbest) when no convergence

	# Rainfall interception model
	Lai_2_SintMax = false # <true> derive Sint_Sat from LAI_2_SINTMAX; <false> derive from input file

	# Step wise optimization
	"σ_2_Ψm⍰" = ":No"  # <:Constrained> Ψm physical feasible range is computed from σ <:UniqueRelationship> Ψm is computed from σ; <:No> optimisation of σ & Ψm with no constraints
	"σ_2_θr" = true # <true> derive θr from σ <false>
	"θs_Opt⍰" = ":No" #  <:θs_Opt⍰> θs is derived by multiplying a parameter to Max(θobs) for all profiles; <No>

	# Calibration data available
	Optimisation = true # <true>; <false>
	"θobs"         = true # <true>; <false>
	"θobs_Average" = true #<true> ; <false>determine if the observed θ is an average of different layers

	"θobs_Hourly" = true # θ data can be very large so we reduce the data to hourly

	# Table true
	Table = true 
	Table_Discretization  = true
	Table_Q               = true
	Table_RootWaterUptake = true
	Table_TimeSeries      = true
	"Table_Ψ"               = true
	"Table_θ"               = true
	Table_TimeSeriesDaily = true
	"Tabule_θΨ"             = true
	Table_Climate         = true

	# plot outputs
	Plot_Vegetation   = false
	"Plot_θΨK"          = false
	Plot_Interception = false
	Plot_Other        = false
	Plot_Sorptivity   = false
	Plot_Hypix        = true
		Plot_Climate      = true
		"Plot_θ"            = true
		"Plot_Ψ"            = true
		Plot_Flux         = true
		Plot_WaterBalance = true
		"Plot_ΔT"           = true