[globalparam]
	N_iZ_Plot_Start  = 1 # Starting of iZ to be plotted
	N_iZ_Plot_End    = 100000 # End of iZ to be plotted

[hydro]
	"Coeff_Φ_2_θs" = 0.95 # 0.95

	# Bimodal
		"θs_θsMacMat" = 0.05 # Treshold when the model is classified as Bimodal if θs - θsMacMat > θs_θsMacMat

	# If σMac and ΨmMac are constants
		"ΨmacMat" = 100.0 # 50-150 [mm] determine when matrix and macro domain 
		"Ψ_Max"  = 160_000.0 # [mm] min value is 150000 mm and oven dry would be the best value 
		
	# Output in tables
		"TableComplete_θΨ" = [0.0, 10.0, 50.0, 100.0, 500.0, 1000.0, 2000.0, 3300.0, 4000.0, 5000.0,100_00.0, 500_00.0, 1000_00.0, 1500_00.0,  2000_00.0] # mm

		K_Table =  [0.0, 10.0, 100.0, 500.0, 1000.0, 2000.0, 4000.0, 10000.0] # mm

		# computing ΨmMac and σMac
			# "ΨmMac" = 10.0 #$ √ΨmacMat [mm]

		#----------------------
		# .kg KOSUGI PARAMETERS
		#----------------------		
		[hydro.kg]
			"Ψσ_Min" =  10.0 #ΨmMac # [mm]
			"Ψσ_Max" =  100.0 # [mm]
			"Ψσ" = 31.62277 # exp((log(Ψσ_Min) + log(Ψσ_Max)) / 2.0)  # 1.0 # [mm] used if option.σ_2_Ψm⍰ = # <:UniqueRelationship> 

[smap]	
	"Ψ_Table" = [0.0, 500.0, 1000.0, 2000.0, 3300.0, 4000.0,  10000.0,  150000.0 ] # mm

[psd]
	"Psd_2_θr_α1"    = 16.01602133125399 # α1
	"Psd_2_θr_α1_Min" = 0.01
	"Psd_2_θr_α1_Max" = 100.0
	"Psd_2_θr_α2"    = 2.013125380534685 # α2  
	"Psd_2_θr_α2_Min" = 0.001
	"Psd_2_θr_α2_Max" = 10.0
	"Psd_2_θr_Size"   = 1  # size of particle size corresponding to clay fraction
	"Ψ_Table" = [0.0, 500.0, 1000.0, 2000.0, 4000.0, 10000.0, 150000.0] # mm

	[psd.imp]
		# Optimisation of psd
			"Ψ_Max" = 160000.0 # [mm] min value is 150000 mm and oven dry would be the best value  
			"λ" 	  = 2.0 	 # exponent of the normalised Young-Laplace capillary equation # λ = 1 for new table model 1 ######
			"ξ_Max" = 3.0 	 # ξ maximum physical value 

		# Intergranular mixing particle model (imp)
			"ξ1" = 9.040974907360946 # 9.040974907360946 (paper)5.13729 (opt)
				"ξ1_Min" = 0.01 # 0.0 
				"ξ1_Max" =  20.0

			"ξ2_Max" = 0.2  

			"∑Psd_2_ξ2_β1"   = 0.0874077451694647 #0.0874077451694647 (paper)  0.06983 (opt) Relationship which computes ξ2 from ∑Psd
				"∑Psd_2_ξ2_β1_Min" = 0.001 # for new table model 4   # ξ2_Min 
				"∑Psd_2_ξ2_β1_Max" = 0.1   # for new table model 4   # 1.0 

			"∑Psd_2_ξ2_β2"   = 0.9463302042937239 #0.9463302042937239 (paper) 1.40926 (opt)
				"∑Psd_2_ξ2_β2_Min" = 0.1 
				"∑Psd_2_ξ2_β2_Max" = 5.0
				
			"∑Psd_2_ξ2_Size" = 2  # TODO cumulative particle size fraction corresponding to very fine silt
			Subclay        = 0.69422 #0.6934995359806453 (paper) weighted of deriving the smallest particle size
				Subclay_Min = 0.1
				Subclay_Max = 1.0
		
	[psd.chang]
	# Chang param
		"ξ1" = 0.5
			"ξ1_Min" =  0.0 # TODO ξ1_Min chang
			"ξ1_Max" =  1.0 # TODO ξ1_Max chang

[infilt]
	# General parameters
		SeIni_Output = [0.0, 0.2, 0.4, 0.6, 0.8] # [-] Different initial Se_Ini for plotting the infiltration curves 
		Npoint_Infilt = 300 # Number of points for generating infiltration plots
		"ΔSlope_Err_SteadyState" = 0.5 # 0.5 Maximum error of not meeting the slope

[hyPix]
	# Simulation wanted to run 
		iOpt_Start = 1
		iOpt_End   = 3

	# Simulations start end
		Year_Start   = 2015 # 2017
		Month_Start  = 10 #6
		Day_Start    = 18
		Hour_Start   = 9
		Minute_Start = 0
		Second_Start = 0
		Year_End     = 2018
		Month_End    = 5
		Day_End      = 18
		Hour_End     = 9
		Minute_End   = 0
		Second_End   = 0

	# Auto discretisation
		# If auto discretisation is selected to derive the cells sizes
		"ΔZrz_Max"   = 25.00 # [mm] {10-50} maximum discretisation size in the root zone
		"ΔZdeep_max" = 75.00 # [mm] {50-100} maximum discretisation size below the root zone

	# Slope[radiant]
		"Cosα" = 1.0
	
	# Ponding
		"ΔHpondMax" = 15.0 # [mm] for optimisation maximum ponding depth at the end of the simulation before penalty implies 

	# Richards equation
		"Ψ_Bot" = 0.0 # If BottomBoundary⍰ =  [Pressure]

	# Time management
		"ΔT_Min"   = 10.0  # 30.0 [seconds]
		"ΔT_Max"   = 3600.0 # 60.0 * 60.0 / 3.0 [seconds]

	# Iterations
		N_Iter   = 30 # 80 Maximum number of iteration before changing time step
		"ΔT_Rerun" = 1.2 # Allowable change of ΔT without rerun of the model > 1.0
		"Δθ_Max"   = 5.01187E-4			# 3.3 1.0E-3 1.0E-4 Best result between [10^-4.5 ; 10^-5.0] smaller the smaller the time step

	# Newton step
		NewtonStepWeaken = 0.5 # [1 0[ when 1 then no averaging when 0 then uses Ψ from previous time k-1

	# Water balance
		WaterBalanceResidual_Max = 10.0E-11 # 10.0E-11

		#----------------------
		#	obsTheta parameters
		#----------------------
		[hyPix.obsTheta]
			NmaxFuncEvals = 130
		
			# Calibration data start end (if available)
				Year_Start   = 2015
				Month_Start  = 11
				Day_Start    = 18
				Hour_Start   = 9
				Minute_Start = 0
				Second_Start = 0
				Year_End     = 2018 # Does not matter if greater than the dates of observations
				Month_End    = 5
				Day_End      = 18
				Hour_End     = 9
				Minute_End   = 0
				Second_End   = 0
				"θobs_Uncert" = 0.03 # [cm³ cm-³]

	[hyPix.ploting]
		Year_Start   = 2015
		Month_Start  = 10
		Day_Start    = 18
		Hour_Start   = 9
		Minute_Start = 0
		Second_Start = 0
		Year_End     = 2018
		Month_End    = 5
		Day_End      = 18
		Hour_End     = 9
		Minute_End   = 0
		Second_End   = 0
		Cells_Plot = [1, 3, 5, 7, 9, 11, 13]
		"θΨ_Table" = [0.0, 100.0, 200.0, 300.0, 400.0, 500.0, 600.0, 700.0, 800.0, 900.0, 1000.0, 2000.0, 3000.0, 4000.0, 5000.0, 6000.0, 7000, 8000, 9000, 10000.0, 2E4, 3E4, 4E4, 5E4, 6E4, 7E4, 8E4, 9E4, 1E5, 150000.0, 2E5, 3E5, 1E6] # mm